---
apiVersion: v1
kind: Service
metadata:
  name: certbot-forward
  namespace: ircd
spec:
  type: ExternalName
  externalName: xinutec-validation.barfooze.de
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ircd
  name: irc-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - irc.xinutec.net
    secretName: irc-tls
  rules:
  - host: irc.xinutec.net
    http:
      paths:
      - path: /.well-known
        pathType: Prefix
        backend:
          service:
            name: certbot-forward
            port:
              number:  80
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  namespace: ircd
#  name: httpd-irc
#spec:
#  selector:
#    matchLabels:
#      run: httpd-irc
#  replicas: 2
#  template:
#    metadata:
#      labels:
#        run: httpd-irc
#    spec:
#      containers:
#      - name: httpd-irc
#        image: nginx
#        ports:
#        - containerPort: 80
#---
#apiVersion: v1
#kind: Service
#metadata:
#  namespace: ircd
#  name: httpd-irc
#  labels:
#    run: httpd-irc
#spec:
#  ports:
#  - port: 80
#    protocol: TCP
#  selector:
#    run: httpd-irc
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  namespace: ircd
#  name: irc-ingress
#  annotations:
#    cert-manager.io/cluster-issuer: "letsencrypt-staging"
#spec:
#  ingressClassName: nginx
#  tls:
#  - hosts:
#    - irc.xinutec.com
#    secretName: irc-tls
#  rules:
#  - host: irc.xinutec.com
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: httpd-irc
#            port:
#              number:  80
