---
apiVersion: v1
kind: Service
metadata:
  name: certbot-forward
  namespace: ircd
spec:
  type: ExternalName
  externalName: xinutec-validation.barfooze.de
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ircd
  name: irc-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - xinutec.org
    - irc.xinutec.net
    secretName: irc-tls
  rules:
  - host: xinutec.org
    http:
      paths:
      - path: /barfooze #/.well-known
        pathType: Prefix
        backend:
          service:
            name: certbot-forward
            port:
              number:  80
  - host: irc.xinutec.net
    http:
      paths:
      - path: /barfooze #/.well-known
        pathType: Prefix
        backend:
          service:
            name: certbot-forward
            port:
              number:  80
