---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: services
  name: ircd-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  namespace: services
  name: inspircd
  labels:
    run: inspircd
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: ircd-storage
  containers:
    - name: ircd
      image: xinutec/ircd:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 22
      volumeMounts:
        - mountPath: /etc/inspircd/conf/secret
          name: data
          subPath: secret
---
apiVersion: v1
kind: Service
metadata:
  namespace: services
  name: inspircd
spec:
  type: LoadBalancer
  selector:
    run: inspircd
  ports:
    - name: clients
      protocol: TCP
      port: 6697
      targetPort: 6697
    - name: servers
      protocol: TCP
      port: 7005
      targetPort: 7005
