---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: vps
  name: irssi-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vps
  name: irssi-pippijn
spec:
  selector:
    matchLabels:
      run: irssi-pippijn
  template:
    metadata:
      labels:
        run: irssi-pippijn
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: irssi-storage
      containers:
        - name: irssi
          image: xinutec/irssi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 22
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /home/irssi
              name: data
              subPath: pippijn
            - mountPath: /etc/ssh_keys
              name: data
              subPath: ssh
---
apiVersion: v1
kind: Service
metadata:
  namespace: vps
  name: irssi-pippijn
spec:
  type: NodePort
  selector:
    run: irssi-pippijn
  ports:
    - name: ssh
      protocol: TCP
      port: 2222
      targetPort: 22
