---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: web
  name: httpd-amun
spec:
  selector:
    matchLabels:
      run: httpd-amun
  replicas: 2
  template:
    metadata:
      labels:
        run: httpd-amun
    spec:
      volumes:
      - name: assetlinks-config-volume
        configMap:
          name: assetlinks-config
      containers:
      - name: httpd-amun
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: assetlinks-config-volume
          mountPath: /usr/share/nginx/html/.well-known/assetlinks.json
          subPath: assetlinks.json
---
apiVersion: v1
kind: Service
metadata:
  namespace: web
  name: httpd-amun
  labels:
    run: httpd-amun
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: httpd-amun
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: web
  name: amun-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - amun.xinutec.org
    secretName: amun-tls
  rules:
  - host: amun.xinutec.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpd-amun
            port:
              number:  80
