apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: radicale
  labels:
    app: radicale
data:
  config: |-
    [server]
    hosts = 0.0.0.0:5232

    [auth]
    type = http_x_remote_user

    [storage]
    filesystem_folder = /data/collections

    [web]
    type = internal
