---
apiVersion: v1
kind: Namespace
metadata:
  name: web
  labels:
    name: web
---
apiVersion: v1
kind: Service
metadata:
  name: certbot-forward
  namespace: web
spec:
  type: ExternalName
  externalName: xinutec-validation.barfooze.de
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: web
  name: irc-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  rules:
  - host: irc.xinutec.org
    http:
      paths:
      - path: /.well-known
        pathType: Prefix
        backend:
          service:
            name: certbot-forward
            port:
              number:  80
