domain: xinutec.org
hostnames:
  - mail.xinutec.org
initialAccount:
  enabled: true
  username: "mailadmin"
  domain: "xinutec.org"
  #password: ""  # XXX: add here when updating
  mode: "update"
logLevel: INFO
persistence:
  size: 100Gi
  storageClass: local-path
ingress:
  ingressClassName: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
#secretKey: ""  # XXX: add here when updating
