---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nextcloud
  name: nextcloud-server
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-label: nextcloud-server-pod
  template:
    metadata:
      labels:
        pod-label: nextcloud-server-pod
    spec:
      volumes:
      # Create the shared files volume to be used in both pods
      - name: server-storage
        persistentVolumeClaim:
          claimName: nextcloud-storage
      # Add the ConfigMap we declared in nginx-config.yaml as a volume for the pod
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      containers:
      - name: nextcloud
        image: nextcloud:24-fpm-alpine
        imagePullPolicy: Always
        env:
        - name: MYSQL_HOST
          value: nextcloud-db
        - name: MYSQL_DATABASE
          value: nextcloud
        - name: NEXTCLOUD_ADMIN_USER
          value: admin
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: dash.xinutec.org
        - name: TRUSTED_PROXIES
          value: 127.0.0.1 ::1
        - name: OVERWRITEHOST
          value: dash.xinutec.org
        - name: OVERWRITEPROTOCOL
          value: https
        - name: REDIS_HOST
          value: redis-master
        - name: REDIS_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
        envFrom:
        - secretRef:
            name: nextcloud-db-secret
        - secretRef:
            name: nextcloud-server-secret
        volumeMounts:
        - name: server-storage
          mountPath: /var/www/html
          subPath: server-data
      # Our nginx container, which uses the configuration declared in
      # nginx-config.yaml, along with the files shared with the PHP-FPM app.
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: server-storage
          mountPath: /var/www/html
          subPath: server-data
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  namespace: nextcloud
  name: nextcloud-server
  labels:
    app: nextcloud
spec:
  selector:
    pod-label: nextcloud-server-pod
  ports:
  - protocol: TCP
    port: 80
