---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nocodb
  name: nocodb-storage
  labels:
    app: nocodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
