---
name: docker

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      image:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.path }}
          push: true
          tags: xinutec/${{ inputs.image }}:latest
          cache-from: type=registry,ref=xinutec/${{ inputs.image }}:cache
          cache-to: type=registry,ref=xinutec/${{ inputs.image }}:cache
