---
name: docker

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      image:
        required: true
        type: string
      push:
        required: false
        type: boolean
        default: true
    secrets:
      username:
        required: false
      password:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: ${{ inputs.push }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      - name: Build and push
        if: ${{ inputs.push }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.path }}
          push: true
          tags: xinutec/${{ inputs.image }}:latest
          cache-from: type=registry,ref=xinutec/${{ inputs.image }}:cache
          cache-to: type=registry,ref=xinutec/${{ inputs.image }}:cache
      - name: Build only
        if: ${{ ! inputs.push }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.path }}
          tags: xinutec/${{ inputs.image }}:latest
